Lint on git with clean history (#411)
* git: basic reset around lint-local

* git: use a trap to reset in any case!

* git-fix: use double quotes for eslint rule hack (otherwise this does not
work with git)

* git: local-lint in tmp directory if unclean

* git: try to recover reset with lfspre

* git-fix: set unclean manually and do not assign the test directly

* git-fix: store args before running lfspre

* git, refactor: only copy source and test folder, as well as package json and node modules to get eslint running

* git-fix: try to allow lfs locking

* git-fix: revert back to copy everythign from the current dir, just to be save

* git, refactor: try to use git clone

* git, refactor: use hard reset in the other directory

* refactor: minor cleanup of the pre-push hook (remove empty lines)

* git, refactor: clarify `node_modules` to be a folder

diff --git a/.githooks/pre-push b/.githooks/pre-push
--- a/.githooks/pre-push
+++ b/.githooks/pre-push
@@ -2,16 +2,55 @@
 
 set -eu
 
-# run linter
-
 if ! [ -x "$(command -v npm)" ]; then
   echo 'Error: npm not found. Make it available to the host shell (e.g., with "nvm use --lts").'
   exit 2
+fi
+
+
+reset() {
+  echo "Cleaning up and return control"
+  rm -r "$flowrtmpdir"
+  cd "$curdir"
+}
+
+unclean=false
+if [ -n "$(git status --porcelain)" ]; then
+  # if we directly assign the test set -eu will not approve
+  unclean=true
+  echo "Working tree is not clean, so we reset in temporary folder"
+  # backwards compatible platform independence
+  flowrtmpdir=$(mktemp -d 2>/dev/null || mktemp -d -t 'flowrtmpdir')
+  echo "Using temporary folder $flowrtmpdir"
+
+  curdir=$(pwd)
+
+  echo "Cloning copy..." # cloning obeys gitignore
+  git clone . "$flowrtmpdir"
+  echo "Keep installed packages..."
+  cp -r node_modules/ "$flowrtmpdir/node_modules"
+  cd "$flowrtmpdir"
+
+  git reset --hard
+  trap reset EXIT
+  echo "Setup completed."
 fi
 
 echo "Linting project (local mode)..."
 npm run lint-local
 
 
-command -v git-lfs >/dev/null 2>&1 || { echo >&2 "\nThis repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove this hook by deleting '.git/hooks/pre-push'.\n"; exit 2; }
-git lfs pre-push "$@"
+# shellcheck disable=SC2124 # we want the argument splitting
+args="$@"
+lfspre() {
+  if $unclean; then
+    reset
+  fi
+  command -v git-lfs >/dev/null 2>&1 || { echo >&2 "\nThis repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove this hook by deleting '.git/hooks/pre-push'.\n"; exit 2; }
+  # we want the argument splitting
+  git lfs pre-push $args
+}
+
+# we register it as a trap after lint so that it 1) triggers only if lint-local succeeded
+# but 2) only triggers *after* the directory recovery completed
+trap lfspre EXIT
