fix pat haunting my dreams (#1275)
* ci: require expected version in release commit

* ci-fix: fixed version regex

* ci: stop dragging around the version we don't need anymore

* doc: update the data file

diff --git a/.github/workflows/release.yaml b/.github/workflows/release.yaml
--- a/.github/workflows/release.yaml
+++ b/.github/workflows/release.yaml
@@ -142,15 +142,25 @@ jobs:
         id: release
         run: |
           step=$(echo "$MESSAGE" | sed -n -E 's/\[release:(patch|minor|major)].*/\1/p')
-          title=$(echo "$MESSAGE" | sed -n -E 's/\[release:(patch|minor|major)] (.*)/\2/p')
+          version=$(echo "$MESSAGE" | sed -n -E 's/\[release:(patch|minor|major)] ([0-9]+\.[0-9]+\.[0-9]+) .*/\2/p')
+          title=$(echo "$MESSAGE" | sed -n -E 's/\[release:(patch|minor|major)] ([0-9]+\.[0-9]+\.[0-9]+) (.*)/\3/p')
 
           if [ -z "$step" ]; then
             echo "fatal: Release step not found in commit message."
             exit 1
           fi
+          if [ -z "$version" ]; then
+            echo "fatal: Expected version not found in commit message."
+            exit 1
+          fi
+          
+          expected_version=$(npm run release -- --increment "$step" --ci --dry-run --release-version | tail -1)
+          if [ "$version" != "$expected_version" ]; then
+            echo "fatal: Expected version $version does not match calculated version $expected_version."
+            exit 1
+          fi
 
           npm run release -- --increment "$step" --ci --verbose --github.releaseName="Release v\${version} (${title})"
-          echo "version=$(node -p "require('./package.json').version")" >> "$GITHUB_OUTPUT"
         env:
           RELEASE_TOKEN: ${{ secrets.RELEASE_TOKEN }}
           # apparently, putting the message into an env variable first sanitizes it
@@ -170,8 +180,6 @@ jobs:
           npm run publish-library
         env:
           NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
-    outputs:
-      version: ${{ steps.release.outputs.version }}
 
   deploy-docker:
     needs: ['release']
@@ -271,8 +279,6 @@ jobs:
         with:
           name: benchmark-results-${{ matrix.name }}-${{ matrix.parser }}
           path: test/performance/results/
-    outputs:
-      version: ${{ needs.release.outputs.version }}
 
   performance-test-upload:
     name: "⬆️ Upload Performance Test Results"
@@ -285,8 +291,6 @@ jobs:
           submodules: true
           lfs:        true
           token:      ${{ secrets.RELEASE_TOKEN }}
-          # check out the release ref so that the upload action finds the commit
-          ref: "refs/tags/v${{ needs.performance-test.outputs.version }}"
 
       - name: "⚙️ Name and Email for Git (config) and update"
         # we fetch just to be totally sure
@@ -316,7 +320,6 @@ jobs:
           comment-always: true
           skip-fetch-gh-pages: true
           max-items-in-chart: 100
-          ref: "refs/tags/v${{ needs.performance-test.outputs.version }}"
           gh-repository: ${{ github.repository }}
           benchmark-data-dir-path: wiki/stats/benchmark/
           auto-push: false
@@ -340,7 +343,6 @@ jobs:
           comment-always: true
           skip-fetch-gh-pages: true
           max-items-in-chart: 100
-          ref: "refs/tags/v${{ needs.performance-test.outputs.version }}"
           gh-repository: ${{ github.repository }}
           benchmark-data-dir-path: wiki/stats/benchmark/
           auto-push: false
@@ -366,7 +368,6 @@ jobs:
           comment-always: true
           skip-fetch-gh-pages: true
           max-items-in-chart: 100
-          ref: "refs/tags/v${{ needs.performance-test.outputs.version }}"
           gh-repository: ${{ github.repository }}
           benchmark-data-dir-path: wiki/stats/benchmark/
           auto-push: false
@@ -390,7 +391,6 @@ jobs:
           comment-always: true
           skip-fetch-gh-pages: true
           max-items-in-chart: 100
-          ref: "refs/tags/v${{ needs.performance-test.outputs.version }}"
           gh-repository: ${{ github.repository }}
           benchmark-data-dir-path: wiki/stats/benchmark/
           auto-push: false
