ci-fix: improved parsing of step and title of the next release

diff --git a/.github/workflows/release.yaml b/.github/workflows/release.yaml
--- a/.github/workflows/release.yaml
+++ b/.github/workflows/release.yaml
@@ -24,8 +24,14 @@ jobs:
       - name: Release
         run: |
           msg="${{ github.event.head_commit.message }}"
-          step=$(echo "$msg" | sed -n 's/\[release:\(patch|minor|major\)].*/\1/p')
-          title=$(echo "$msg" | sed -n 's/\[release:\(patch|minor|major\)] \(.*\)/\2/p')
+          step=$(echo "$msg" | sed -n -E 's/\[release:(patch|minor|major)].*/\1/p')
+          title=$(echo "$msg" | sed -n -E 's/\[release:(patch|minor|major)] (.*)/\2/p')
+          
+          if [ -z "$step" ]; then
+            echo "fatal: Release step not found in commit message."
+            exit 1
+          fi
+          
           npm run release -- $step --github.releaseName="${title}"
 
   deploy-docker:
